server:
  port: 8888

spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/Recent/Microservices/Microservices-config-server
          default-label: main
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"