server:
  port: 8090


spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: dossier-medical-service
          predicates:
            - Path=/dossier-medical-service/**
          filters:
            - RewritePath=/dossier-medical-service/(?<s>.*), /${s}
            - name: CircuitBreaker
              args:
                name: fallback-dossier-medical-service
                fallbackuri: forward:/dossierMedicalServiceDefaultResponse
          uri: lb://dossier-medical-service

        - id: examen-clinique-service
          predicates:
            - Path=/examen-clinique-service/**
          filters:
            - RewritePath=/examen-clinique-service/(?<s>.*), /${s}
            - name: CircuitBreaker
              args:
                name: fallback-examen-clinique-service
                fallbackuri: forward:/examenCliniqueServiceDefaultResponse
          uri: lb://examen-clinique-service

        - id: gestion-compte-service
          predicates:
            - Path=/gestion-compte-service/**
          filters:
            - RewritePath=/gestion-compte-service/(?<s>.*), /${s}
            - name: CircuitBreaker
              args:
                name: fallback-gestion-compte-service
                fallbackuri: forward:/gestionCompteServiceDefaultResponse
          uri: lb://gestion-compte-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/

  instance:
    hostname: localhost

